
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('alerts').del(),

    // Inserts seed entries
    knex('alerts').insert({title: 'HRDF Update May 2015', date: 'May 3, 2015 1:34 pm', author: 'Admin', image: 'http://www.hrdforum.org/wp-content/uploads/2016/01/Untitled-1-1.jpg', body: 'In April and May, authorities sentenced prominent human rights defenders to harsh prison sentences for participating in peaceful demonstrations against two widely condemned deaths perpetrated by Burma’s military and police.'}),

    knex('alerts').insert({title: 'HRDF Update April 2015', date: 'April 28, 2015 2:31 pm', author: 'Admin', image: 'http://www.hrdforum.org/wp-content/uploads/2015/12/Untitled-1-1.jpg', body: 'Seventy students and supporters remain in detention in Tharawaddy Prison, Pegu Division, one month after the police crackdown in Letpadan. Twelve students and supporters are also facing charges for participating in solidarity protests in Rangoon and Myingan, Mandalay Division.  Among the 70 detained in Tharawaddy Prison are All Burma Federation of Student Unions (ABFSU) leaders Phyoe Phyoe Aung, Aung Hmine San, Moe Htet Nay, Thiha Win Tin, Hanny Oo, Nandar Sitt Aung, and Min Thway Thit.  At a 25 March hearing, the Letpadan Township Court charged 69 people detained on 10 March under Article 143 (unlawful assembly), Article 145 (joining or continuing in unlawful assembly), Article 147 (rioting), Article 332 (voluntarily causing harm to deter public servants), and Article 505 (b) (public mischief) of the Criminal Code. If convicted of all charges, students face up to nine and a half years in prison. On the same day, the Letpadan Township Court charged another 11 people detained on 10 March under Articles 143, 145, and 147 of the Criminal Code, but released them on bail. Those released without charges had to first sign a statement stating they would no longer be involved in the protests.'}),

    knex('alerts').insert({title: 'HRDF Update July 2015', date: 'July 30, 2015 4:40 am', author: 'Admin', image: 'http://www.hrdforum.org/wp-content/uploads/2015/12/Untitled-1-6.jpg', body: 'In July, the extrajudicial killing of a land rights defender in Karen State highlighted the ongoing risk faced by HRDs in Burma. On 2 July, in the early hours of the morning, unknown assailants shot and killed land rights defender and local National League for Democracy (NLD) leader Saw Johnny in front of his home in Eindea Village, Hpa-an Township, Karen State. Saw Johnny’s 14-year-old daughter heard shots and found him still breathing before he passed away a few moments later. While investigating the scene, police found eight bullet holes in Saw Johnny’s back and leg. Ten bullet casings were also found at the scene. The case is currently under police investigation.'}),

    knex('alerts').insert({title: 'HRDF Update May 2015', date: 'May 3, 2015 1:34 pm', author: 'Admin', image: 'http://www.hrdforum.org/wp-content/uploads/2015/12/Untitled-1-3.jpg', body: 'From 3 to 7 August 2015, United Nations Special Rapporteur on the situation of human rights in Burma Yanghee Lee conducted her third official visit to the country. In a 7 August statement, Lee referenced a number of legal issues affecting HRDs: HRDs and civil society actors reported increased monitoring and surveillance of their activities, and increased intimidation and harassment by security personnel and state agents.  HRDs and journalists faced threats and intimidation by religious extremists.  Political prisoners remained behind bars.  Authorities continued to use Article 18 of the Peaceful Gathering and Demonstration Law and Article 505(b) of the Criminal Code against those exercising their rights to freedom of expression, assembly, and association.  Authorities continued to arrest and convict civil society actors (including students, political activists, workers, union leaders, farmers, and community organizers) for exercising their rights to freedom of expression, assembly, and association.  Authorities continued to arrest and convict individuals involved in protests related to land rights, extractive industries, and large-scale development projects.  Authorities continued to arrest journalists and media professionals under defamation, harassment, trespassing, and national security laws.'})
  );
};
